---
jira:
  projectKey: "HSEARCH"
  ignoreFiles:
    - ".github"
    - "ci"
    - "build/config"
    - "Jenkinsfile"
    - "*/Jenkinsfile"
    - "*.Jenkinsfile"
develocity:
  buildScan:
    addCheck: true
    tags:
      - column: "OS"
        pattern: "Linux"
      - column: "OS"
        pattern: "Windows.*"
        replacement: "Windows"
      - column: "Java"
        pattern: "jdk-(.*)"
        replacement: "$1"
      - column: "Backend"
        pattern: "elasticsearch-(.*)"
        replacement: "es-$1"
      - column: "Backend"
        pattern: "(.*-)?opensearch-(.*)"
        replacement: "$1os-$2"
      - column: "Backend"
        pattern: "lucene"
      - column: "DB"
        pattern: "h2|postgres|postgres(ql)?|mysql|mssql|derby|tidb|cockroach(db)?|oracle.*|db2"
        replacement: "$0"
      - pattern: "hibernate.search|elasticsearch|opensearch|main|\\d+.\\d+|PR-\\d+"
        replacement: "" # Just remove these tags
